### ISSUE TITLE
Alt-A must not be used as the global key comb

### ISSUE THREAD

**Issue by rdar-lab** [Jongy/zoom_unmuter#3]
If using the same key comb as the zoom's default key for unmute/mute it creates a loop which of calls

**Comment by Jongy** [comment]
What do you mean? When running `install.sh` you must specify the key combination for the global mute/unmute; later on, `zoom_key_send.sh` uses Alt+A to send the mute/unmute command to zoom. There's no default "global combination".

**Comment by rdar-lab** [comment]
Try to use the install.sh with the key combination Alt-A.
Now, when you press Alt-A , zoom_key_send triggers the focus on the zoom application and sends Alt-A which triggers the "zoom_key_send.sh" **again**, and over and over...

**Comment by Jongy** [comment]
Ah, I see what you're saying. I've originally used it with a different key-combination that the one used by Zoom, so it worked. I suppose that we can wrap the script with some file-based locking that'll prevent the recursion and allow you to use Alt+A as the key. I'll accept such a PR

**Comment by rdar-lab** [comment]
For now I suggest to update the. README.md with this limitation.
